### ISSUE TITLE
Jegy

### ISSUE THREAD

**Issue by hegyhati** [Teaching-projects/SZE-FordProg-2020-C--Tokenizer#1]
2-es megvan igy. 4/5 ebbol igy ebben a formaban nem jon ki. Lenyegeben a tanultakbol semmi nincs hasznositva, nem latok nyelvtant (ha netan van, akkor mutass ra kerlek).

3-as talan meglehet. 

Ha eziranyba szeretnenk menni, akkor az elso, amit kerek, hogy takaritsd ki a repot, ne legyenek ott a binarisok, legyen egy normalis gitignore. Emellett a readme jobban emelje ki, hogy mi hol van, legyen bemutatva egy futas vagy valami. (En ezt igy nem tudom futtatni, kiprobalni). Aztan a tobbit majd meglatjuk.

**Comment by slidercod4** [comment]
Elfogadnám a 2-est a köszönöm szépen! :)

**Comment by hegyhati** [comment]
Rendben, akkor jelentkezz fel vizsgara, aztan majd amikor lesz, beirom a jegyet, tovabbi teendod nincs. :-)
